### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by ttimot24**
Updating monolog version to 2.* to avoid dependency conflicts

### CODE REVIEW

**Comment by thelfensdrfer** [comment]
I am afraid it is just a little extra work. I had to upgrade php to >= 7.2, because of monolog 2, which is not a problem at all. Currently working on it and making a release later today.

**Comment by ttimot24** [comment]
Thank you very much! It's a huge help :)

**Comment by ttimot24** [comment]
Thank you!

As I see if phpunit 8 is used than you don't have to drop PHP 7.2. Since it still supported until November 2020

**Comment by thelfensdrfer** [comment]
In its current version monolog also requires php >= 7.2: https://github.com/Seldaek/monolog/blob/ed2a226ebe210fecd5f74ca5a126793294c31b1d/composer.json

**Comment by thelfensdrfer** [comment]
No, you are totally correct. I mixed up the versions. Now it should work with php 7.2 again. Thanks!

**Pull request closed without merging**
